seed: 42
device: "cpu"     # set "cuda" if GPU is available
data:
  train_path: "data/train.csv"
  val_path: "data/val.csv"
  target_col: "label"
  id_col: "sample_id"
  feature_groups:
    - prefix: "gen_"     # genomics
    - prefix: "tx_"      # transcriptomics
    - prefix: "epi_"     # epigenomics
    - prefix: "prot_"    # proteomics
    - prefix: "clin_"    # clinical
    - prefix: "sc_"      # single-cell (summary features)
    - prefix: "sp_"      # spatial transcriptomics (summary features)
graph:
  path: "graphs/feature_graph.npy"   # adjacency for features (F x F), built from feature groups
train:
  batch_size: 32
  epochs: 6
  lr: 1e-3
  weight_decay: 1e-4
  num_workers: 2
model:
  hidden_dims: [256, 128]   # GCN layer outputs
  dropout: 0.2
  use_attention: true
eval:
  metrics: ["auroc", "aupr", "accuracy"]
  threshold: 0.5
save:
  dir: "results"
  model_name: "model.pt"